# Generated by Django 2.2 on 2020-03-13 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('C', 'Cardio'), ('DA', 'Dance'), ('M', 'Martial Arts'), ('T', 'How To/Tutorial'), ('CY', 'Cycling'), ('H', 'Hi-Intensity'), ('CO', 'Core'), ('M', 'Mind and Body'), ('ST', 'Sculpting & toning')], default='C', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='P', max_length=1),
            preserve_default=False,
        ),
    ]
