# Generated by Django 2.2.4 on 2020-04-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200412_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='stock_no',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
