# Generated by Django 2.2.14 on 2022-07-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190630_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.CharField(default='negro', max_length=100),
            preserve_default=False,
        ),
    ]
