# Generated by Django 2.2.14 on 2022-11-21 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_delivery_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deleteTag',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
