# Generated by Django 2.2 on 2020-03-15 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200315_1402'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='orderitem',
    #         name='user',
    #         field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
    #     ),
    # ]
