# Generated by Django 2.2.14 on 2022-12-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20221201_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
