# Generated by Django 2.2.14 on 2022-12-01 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20221201_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('FU', 'Furniture'), ('VE', 'Vehicles'), ('CLT', 'Clothes'), ('OUT', 'Outdoor'), ('BP', 'Backpacks')], max_length=2),
        ),
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.URLField(),
        ),
    ]
