# Generated by Django 2.2 on 2020-03-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_item_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.CharField(default='', max_length=7),
        ),
    ]
