# Generated by Django 2.2 on 2020-03-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200315_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='date',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='time',
            field=models.TextField(default=''),
        ),
    ]
