# Generated by Django 2.2 on 2020-03-15 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20200315_2306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date',
            new_name='label',
        ),
    ]
